name: "aparcare-top-up cron job"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  renew_ticket:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls
          python3 renew_ticket.py IGUALADA anymail@gmail.com any-password any-plate