name: "aparcare-top-up cron job"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  renew_ticket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install pytest-playwright
      - run: python3 -m playwright install chromium
      - run: python3 renew_ticket.py ${{ secrets.CITY }} ${{ secrets.email }} ${{ secrets.PASSWORD }} ${{ secrets.CAR }}